### PR TITLE
Add stringable check in @slots

### PR DESCRIPTION
**Pull request by JimmyHoenderdaal**

### CODE REVIEW

**Comment by indykoning** [comment]
To get an idea of what's going on in the code here, what does this PR fix? Do you have some examples?

**Comment by Jade-GG** [comment]
When you're using the `@slots` directive alongside a prop of the same name, the value of the prop gets sent into the slot if it's a string. However, sometimes you also have something that's stringable (like a Statamic value) which you'd expect to also work like this, except it doesn't. You'd have to explicitly cast them to string in the property which feels unnecessary.

This update allows stringable objects to be used without the need to cast them to string explicitly.

**Comment by indykoning** [comment]
Do you have a code example for me? My concern is that ComponentSlots themselves are Stringable as well making you lose the attributes when you have defined a named slot.

As far as i can see this works without unexpected side effects since the Stringable is already rendered in the slot
```blade
<x-component>
    Regular slot text
    <x-slot:optionalSlot class="text-lg">{{ $statamicStringableValue  }}</x-slot:optionalSlot>
</x-component>
```

**Comment by JimmyHoenderdaal** [comment]
```html
<x-component :title="$title" :$id>
...
</x-component>
```
This is the example where it went wrong, the title comes from Statamic. Putting (string) before the title did make it work.

**Comment by indykoning** [comment]
With there being a relatively simple solution, i think it's best to close this instead of risking instability and possible breakages of `@slot` usages

**Pull request closed without merging**
